version: '3.8'
services:
  postgres:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-analytics}
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d

  etl:
    build: .
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_NAME: ${DB_NAME:-analytics}
      DB_USER: ${DB_USER:-postgres}
      DB_PASSWORD: ${DB_PASSWORD:-password}
      API_URL: ${API_URL:-https://jsonplaceholder.typicode.com/posts}
    volumes:
      - .:/app

volumes:
  postgres_data: